### ISSUE TITLE
Error in rval[i, j, drop = drop., ...] : subscript out of bounds (eventstudies)

### ISSUE THREAD

**Issue by D-m-o-j** [nipfpmf/eventstudies#18] opened 2023-05-13 07:42 UTC
Hi, I am trying to run an event study model using the market model and i get the error: Error in rval[i, j, drop = drop., ...] : subscript out of bounds.

When I run the event study using the type="None"  it runs fine but when I use type = "marketModel" that fails.

This is the code:
es1 <-eventstudy(firm.returns = pret,
                 event.list = SplitDates,
                 event.window = 2,
                 type = 'marketModel', #Here we use the market model
                 to.remap = TRUE,
                 remap = 'cumsum',
                 inference = TRUE,
                 inference.strategy = 'bootstrap',
                 model.args = list(
                   market.returns = index[,"BET", drop = FALSE] #Here we specify what benchmark we will use
                 ))

I made sure  that the daates start, are and end the same. The number of observations is the same.

Extra info about the data sets:

> class(pret)
[1] "zoo"
pret contains 17 companies
> class(SplitDates)
[1] "data.frame"
> class(index)
[1] "zoo"
index contains 2 indexes 

Any help in debugging this error is much appreciated.

**Comment by Toodlepoodle** [comment] 2023-05-15 04:39
Hi, can you show how the index[,"BET",drop = FALSE] looks like? 
Also can you provide a snapshot of: -  
a) head(pret) 
b) head(SplitDates)

**Comment by D-m-o-j** [comment] 2023-05-16 18:23
![image](https://github.com/xKDR/eventstudies/assets/133482007/a6156cc5-97b2-4467-afe6-68d6d9ed8769)

a)
![image](https://github.com/xKDR/eventstudies/assets/133482007/9fb8755e-cca7-4ba9-9551-4e344ccc172d)

b)
![image](https://github.com/xKDR/eventstudies/assets/133482007/5f65a4f3-c6d7-40b9-a337-741cad55c5e4)

**Comment by Toodlepoodle** [comment] 2023-06-16 06:36
Hi,
Can you provide these in a format that can be copied and reused
You can use 
```
paste data of head(dataframe) here
```
Then its easier to replicate your error.

**Comment by chiraganand** [comment] 2024-03-19 14:43
Duplicate of #6, solution at: https://github.com/xKDR/eventstudies/issues/6#issuecomment-631949616

**Closed as completed by chiraganand** 2024-03-19 14:43 UTC
